#!/usr/bin/env python3
#
# Copyright (C) 2024 The Evolution X Project
#               2024 crDroid Android Project
#
# SPDX-License-Identifier: Apache-2.0
#
"""Regenerates the alternate indexes and mbn.mk from mcfg_sw/generic.

Nothing here replaces stock's mbn_sw.txt. The configurations are installed
unindexed, so a device that never enables the feature is byte-identical to
stock; init binds one of these indexes over mbn_sw.txt when it is enabled.

Run after adding or removing a configuration; never edit the outputs by hand.

    ./generate.py [path/to/stock/mbn_sw.txt]
"""

import os
import sys

DEST = "$(TARGET_COPY_OUT_VENDOR)/rfs/msm/mpss/readonly/vendor"
HERE = os.path.dirname(os.path.abspath(__file__))

# Pass argv[1] when running outside a build tree.
STOCK = ("../../../../vendor/google/redfin/proprietary/vendor/rfs/msm/mpss/"
         "readonly/vendor/mbn/mcfg_sw/mbn_sw.txt")

BACKSLASH = " \\\n"

PREAMBLE = """#
# Copyright (C) 2024 The Evolution X Project
#               2024 crDroid Android Project
#
# SPDX-License-Identifier: Apache-2.0
#
# Generated by generate.py - do not edit.
#
# stock's mbn_sw.txt is deliberately NOT replaced. These configurations sit in
# vendor unindexed, which the modem ignores, so a device that never turns the
# feature on behaves exactly as it did before. init binds mbn_sw_merged.txt or
# mbn_sw_module.txt over mbn_sw.txt when the user asks for it.

PRODUCT_COPY_FILES += \\
"""


def main():
    os.chdir(HERE)

    # Relative to mcfg_sw/generic, e.g. Pixel/EU/DT/Commercial/CZ/...
    configs = sorted(
        os.path.relpath(os.path.join(d, f), "mcfg_sw/generic").replace(os.sep, "/")
        for d, _, fs in os.walk("mcfg_sw/generic")
        for f in fs
        if f == "mcfg_sw.mbn"
    )


    stock_path = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, STOCK)
    if not os.path.exists(stock_path):
        sys.exit("stock index not found at %s" % stock_path)
    stock = [l.strip() for l in open(stock_path) if l.strip()]

    ours = ["mcfg_sw/generic/%s" % c for c in configs]

    # Stock entries first, in order: dropping them loses working carriers.
    seen = set(stock)
    merged = stock + [p for p in ours if p not in seen]
    with open("mcfg_sw/mbn_sw_merged.txt", "w") as fh:
        fh.write("\n".join(merged) + "\n")

    # Ours alone, for anyone who wants the module's set and nothing else.
    with open("mcfg_sw/mbn_sw_module.txt", "w") as fh:
        fh.write("\n".join(ours) + "\n")

    # The second index the modem reads. Not interchangeable with the above:
    # these paths are resolved against mcfg_sw/generic/ and so omit it. Shipped
    # under a placeholder name; the toggle binds it over oem_sw.txt, which
    # stock does not ship at all.
    with open("mcfg_sw/oem_sw_mod.txt", "w") as fh:
        fh.writelines("mcfg_sw/%s\n" % c for c in configs)

    installed = sorted(
        p for p in (
            os.path.join(d, f).replace(os.sep, "/")
            for d, _, fs in os.walk("mcfg_sw")
            for f in fs
        )
    )
    with open("mbn.mk", "w") as fh:
        fh.write(PREAMBLE.format(dest=DEST))
        fh.write(BACKSLASH.join(
            "    packages/apps/PixelParts/mbn/%s:%s/mbn/%s" % (p, DEST, p)
            for p in installed) + "\n")

    print("%d configurations; merged index %d entries (%d stock kept), "
          "module-only index %d; %d files installed"
          % (len(configs), len(merged), len(stock), len(ours), len(installed)))


if __name__ == "__main__":
    main()
