#!/usr/bin/env python3
#
# Copyright (C) 2024 The Evolution X Project
#               2024 crDroid Android Project
#
# SPDX-License-Identifier: Apache-2.0
#
"""Regenerates mbn_sw.txt, oem_sw.txt and mbn.mk from mcfg_sw/generic.

Run after adding or removing a configuration; never edit the three by hand.

    ./generate.py [path/to/stock/mbn_sw.txt]
"""

import os
import sys

DEST = "$(TARGET_COPY_OUT_VENDOR)/rfs/msm/mpss/readonly/vendor"
HERE = os.path.dirname(os.path.abspath(__file__))

# Pass argv[1] when running outside a build tree.
STOCK = ("../../../../vendor/google/redfin/proprietary/vendor/rfs/msm/mpss/"
         "readonly/vendor/mbn/mcfg_sw/mbn_sw.txt")

BACKSLASH = " \\\n"

PREAMBLE = """#
# Copyright (C) 2024 The Evolution X Project
#               2024 crDroid Android Project
#
# SPDX-License-Identifier: Apache-2.0
#
# Generated by generate.py - do not edit.

# Prepended, not appended: a duplicate PRODUCT_COPY_FILES destination resolves
# in favour of the first entry and the rest are dropped silently.
PRODUCT_COPY_FILES := \\
    packages/apps/PixelParts/mbn/mcfg_sw/mbn_sw.txt:{dest}/mbn/mcfg_sw/mbn_sw.txt \\
    $(PRODUCT_COPY_FILES)

PRODUCT_COPY_FILES += \\
"""


def main():
    os.chdir(HERE)

    # Relative to mcfg_sw/generic, e.g. Pixel/EU/DT/Commercial/CZ/...
    configs = sorted(
        os.path.relpath(os.path.join(d, f), "mcfg_sw/generic").replace(os.sep, "/")
        for d, _, fs in os.walk("mcfg_sw/generic")
        for f in fs
        if f == "mcfg_sw.mbn"
    )

    # Not interchangeable: oem_sw.txt omits the mcfg_sw/generic/ prefix that
    # mbn_sw.txt includes.
    with open("mcfg_sw/oem_sw.txt", "w") as fh:
        fh.writelines("mcfg_sw/%s\n" % c for c in configs)

    stock_path = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, STOCK)
    if not os.path.exists(stock_path):
        sys.exit("stock index not found at %s" % stock_path)
    stock = [l.strip() for l in open(stock_path) if l.strip()]

    # Stock entries first, in order: dropping them loses working carriers.
    seen = set(stock)
    merged = stock + [p for p in ("mcfg_sw/generic/%s" % c for c in configs)
                      if p not in seen]
    with open("mcfg_sw/mbn_sw.txt", "w") as fh:
        fh.write("\n".join(merged) + "\n")

    # mbn_sw.txt comes from the preamble instead.
    installed = sorted(
        p for p in (
            os.path.join(d, f).replace(os.sep, "/")
            for d, _, fs in os.walk("mcfg_sw")
            for f in fs
        ) if p != "mcfg_sw/mbn_sw.txt"
    )
    with open("mbn.mk", "w") as fh:
        fh.write(PREAMBLE.format(dest=DEST))
        fh.write(BACKSLASH.join(
            "    packages/apps/PixelParts/mbn/%s:%s/mbn/%s" % (p, DEST, p)
            for p in installed) + "\n")

    print("%d configurations, %d index entries (%d stock kept), %d appended files"
          % (len(configs), len(merged), len(stock), len(installed)))


if __name__ == "__main__":
    main()
