#!/usr/bin/env python3
#
# Copyright (C) 2024 The Evolution X Project
#               2024 crDroid Android Project
#
# SPDX-License-Identifier: Apache-2.0
#
"""Regenerates oem_sw.txt and mbn.mk from the contents of mcfg_sw/generic.

Run from this directory after adding or removing a configuration. Never edit
either output by hand - an index that disagrees with the tree it names is the
whole reason the stock mbn_sw.txt is left alone.
"""

import os

DEST = "$(TARGET_COPY_OUT_VENDOR)/rfs/msm/mpss/readonly/vendor"
HERE = os.path.dirname(os.path.abspath(__file__))

HEADER = """#
# Copyright (C) 2024 The Evolution X Project
#               2024 crDroid Android Project
#
# SPDX-License-Identifier: Apache-2.0
#
# Generated by generate.py - do not edit. Extra modem carrier configurations,
# indexed only by oem_sw.txt so that the stock mbn_sw.txt and mbn_sw.dig are
# left byte for byte as they shipped.

PRODUCT_COPY_FILES += \\
"""


def main():
    os.chdir(HERE)

    # oem_sw.txt paths are "mcfg_sw/<path>", resolved by the modem against
    # mcfg_sw/generic/.
    configs = sorted(
        os.path.relpath(os.path.join(d, f), "mcfg_sw/generic").replace(os.sep, "/")
        for d, _, fs in os.walk("mcfg_sw/generic")
        for f in fs
        if f == "mcfg_sw.mbn"
    )
    with open("mcfg_sw/oem_sw.txt", "w") as fh:
        fh.writelines("mcfg_sw/%s\n" % c for c in configs)

    installed = sorted(
        os.path.join(d, f).replace(os.sep, "/")
        for d, _, fs in os.walk("mcfg_sw")
        for f in fs
    )
    with open("mbn.mk", "w") as fh:
        fh.write(HEADER)
        fh.write(" \\\n".join(
            "    packages/apps/PixelParts/mbn/%s:%s/mbn/%s" % (p, DEST, p)
            for p in installed) + "\n")

    print("%d configurations, %d installed files" % (len(configs), len(installed)))


if __name__ == "__main__":
    main()
